- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Import VPC Variables
      include_vars: vars/vpc_setup

    - name: create a VPC with dedicated tenancy and a couple of tags
      ec2_vpc_net:
         name: Rag_dev3
         cidr_block: 10.10.0.0/16
         region: us-east-1
         tags:
           module: ec2_vpc_net
           this: works
         tenancy: dedicated