- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Import VPC Variables
      include_vars: vars/vpc_setup

    - name: create a VPC
      ec2_vpc_net:
         name: Module_e2
         cidr_block: 172.20.0.0/16
         region: us-east-1
         dns_support: yes
         dns_hostnames: yes
         state: present
         tendency: default
